version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=user
      - POSTGRES_DB=todo
  app:
    image: my-app
    ports:
      - 1300:3000
